CREATE TABLE devices (device_id text, name text, key text);
INSERT INTO devices (device_id, name, key) VALUES ('02', 'Fake Device 02', 'Fake key 02');
INSERT INTO devices (device_id, name, key) VALUES ('01', 'name 01', 'key 01');
INSERT INTO devices (device_id, name, key) VALUES ('04', 'nombre 04', 'key 04');
INSERT INTO devices (device_id, name, key) VALUES ('00', 'Fake Device 00', 'Fake Key 00');
INSERT INTO devices (device_id, name, key) VALUES ('id_03', 'name_03', 'Fake 03 key');
INSERT INTO devices (device_id, name, key) VALUES ('03', 'Fake Device 3', 'Fake 3 key');
INSERT INTO devices (device_id, name, key) VALUES ('id_04', 'nombre_04', 'Fake 04 key');
CREATE TABLE users (user_id text, name text, key text);
INSERT INTO users (user_id, name, key) VALUES ('1', 'Ana', 'admin123');
INSERT INTO users (user_id, name, key) VALUES ('2', 'Beto', 'user123');
INSERT INTO users (user_id, name, key) VALUES ('3', 'Hola<script>alert("hack")</script>', 'admin123');
INSERT INTO users (user_id, name, key) VALUES ('4', ' OR 1 =1', 'admin123');
INSERT INTO users (user_id, name, key) VALUES ('5', 'Hola&ltscript&gtalert(hack)&lt/script&gt', 'admin123');
INSERT INTO users (user_id, name, key) VALUES ('6', 'Hola&ltscript&gtalert(hack)&lt/script&gt', 'admin123');
